### ISSUE TITLE
1/0 and 0/1

### ISSUE THREAD

**Issue by chl2** [IndigoFloyd/SoyDNGPNext#2]
发现您给的demo数据里有1/0
但是在代码中这些是1和2的表示，
temp_series = df[column].replace({r'1/1': '1', r'1|1': '1', r'0/1': '2', r'0|1': '2',})
所以1/0就表示成了用3表示，
是否应该是
temp_series = df[column].replace({r'1/1': '1', r'1|1': '1', r'0/1': '2', r'0|1': '2', r'1/0': '2', r'1/0': '2'})
这样呢？

**Comment by IndigoFloyd** [comment]
是的，有些情况由于数据中没有，我们没有考虑。针对自己的数据集需要修改映射dict。感谢反馈。
